### ISSUE TITLE
Redesign AutoWidget Shortcut Menu

### ISSUE THREAD

**Issue by drinfernoo** [drinfernoo/plugin.program.autowidget#1]
Currently, when using AutoWidget to define paths in groups, the add-on shows a dialog with a simple "Launch Dialog" button, which *then* opens the skins' provided `script-skinshortcuts.xml`. The reasoning behind this was because it doesn't appear to be possible to call `RunScript(script.skinshortcuts,type=manage&amp;group=mygroup)` using `xbmc.executebuiltin(...)` from Python.

Unfortunately, this leads to a couple of drawbacks. Firstly, the "Launch Dialog" dialog seems redundant and is very *plain*, at the moment. Secondly, the skin-provided `script-skinshortcuts.xml` may include custom properties and such that aren't relevant to AutoWidget's functions. The only properties that AutoWidget uses right now are the `label` and `action` properties, read from `xml` tags that are generated by Skin Shortcuts. It would be nice if in the future, more custom properties could be used, such as widget aspect, icons, and such... but since they can often vary radically between skins, that may not be feasible.

Hopefully, I can convince @jurialmunkey to help me make a new custom window 😁

**Comment by jurialmunkey** [comment]
I think the ideal thing would be to reuse skin shortcuts dialog, as skinning additional dialogs are a pain and skinners don't often put as much effort into them. 

If you use the skinshortcuts xml as a base, you should be able to hide controls using the setVisible() method of the control class.
https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__control.html#ga4216f631d000e8577733dca2ea7d09cf

The window class of xbmcgui also has a removeControl() method. Not sure if it only works with controls added with addControl() or it also works with ones defined in the xml.
https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__window.html#gad0106065ffa09f4b3cf55317da803074

For instance:
```python
window = xbmcgui.Window(xbmcgui.getCurrentWindowDialogId())
mycontrol = window.getControl(ID)  # Replace ID with control ID
mycontrol.setVisible(False)  # Hide control
window.removeControl(mycontrol)  # Remove control
```

**Comment by drinfernoo** [comment]
How can I use the standard Skin Shortcuts dialog, without getting the one from the skin? I would assume I'd need to copy the whole file into my project, but at that point, can't I just delete any controls I don't need?

**Comment by jurialmunkey** [comment]
> 
> 
> How can I use the standard Skin Shortcuts dialog, without getting the one from the skin? I would assume I'd need to copy the whole file into my project, but at that point, can't I just delete any controls I don't need?

If you give it a different name and therefore make it a separate dialog, which then needs to be skinned separately and thus defeats the whole purpose of what I'm suggesting.

For addon dialogs, if the same filename xml exists in the skin folder, then Kodi will always use the skin's version. So if you use the same dialog name as skinshortcuts and hide/remove controls via python, then the addon will use the already existing (and thus already skinned) dialog from the skin.

**Comment by jurialmunkey** [comment]
> 
> 
> How can I use the standard Skin Shortcuts dialog, without getting the one from the skin? I would assume I'd need to copy the whole file into my project, but at that point, can't I just delete any controls I don't need?

That's the whole point. You re-use the already skinned dialog and simply hide/remove the controls that you don't need via Python. That way the skinner doesn't need to skin yet another dialog. 

Skinning additional addon dialogs is a major PITA and should be avoided where-ever possible. 

A lot of work was done in Jarvis and Krypton to combine dialogs to reduce unnecessary skinning load. Plus, a reduced number of dialogs ensures greater consistency of design because there aren't 10 different files that need to be changed all with different controls and IDs.

**Comment by drinfernoo** [comment]
@jurialmunkey Ah, I see. I'll take a look at doing that. Any idea why I can't launch the dialog from Python, and have to do it from `xml`?

**Comment by jurialmunkey** [comment]
You should be able to run it from python. I run scripts from TMDbHelper plugin.

**Comment by jurialmunkey** [comment]
For example see: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/container.py#L533-L539

I run that from a plugin path and it executes correctly.

**Comment by drinfernoo** [comment]
That's what I expected as well... But it doesn't seem to work with Skin Shortcuts :(

**Comment by jurialmunkey** [comment]
Remove the `&amp;` and replace with `&`.

`xbmc.executebuiltin("RunScript(script.skinshortcuts,type=manage&group=mygroup)")`

Predefined character entities such as `&amp;` are only used in XML (e.g. skins). In XML specs, `&` `<` `>` are all reserved characters and so need to be escaped as an entity when used as a string.

Since Python uses a backslash `\` to escape reserved characters, the `&amp;` is treated as a string literal and is never translated into `&` - making your second param `amp;group=` which is invalid.

**Comment by drinfernoo** [comment]
Wow, I never would've figured that out! 😆 It totally works now. Just to figure out this window thing next...

**Comment by drinfernoo** [comment]
I've completely dropped this functionality from the add-on, with everything being managed by AutoWidget via a toggleable context menu item.

**Comment by jurialmunkey** [comment]
The context menu functionality is next level! Well done! Makes setup so easy now.

**Comment by drinfernoo** [comment]
@jurialmunkey Glad to hear it! I actually found that I was able to be much more consistent with the paths I could support by basing everything off of what information I could get from the context menu, rather than what asking Shortcuts returned... so I stuck with that 😅
