### ISSUE TITLE
[Request] Add a widget health check

### ISSUE THREAD

**Issue by BinaryAssault** [drinfernoo/plugin.program.autowidget#102]
It's pretty often that something in one of autowidgets go south causing Kodi to crash.

This is no fault of autowidget. But instead of crashing Kodi, it'd be nice if I could go into auto widget and have a Check Health option that could report issues with autowidgets and maybe even disable or modify them. 

Currently, when the issue happens. If I go look at active widgets in autowidget, I get an error saying check the Kodi log. 

To mention, this on Windows using 64bit matrix. In my experience, Windows Kodi is less stable than the Linux variants. 

I can provide a log, but that isn't what this is about. This is a request a way to troubleshoot issues with autowidgets.

**Comment by drinfernoo** [comment]
The log is the way to troubleshoot issues.

**Comment by BinaryAssault** [comment]
Of course the log is a good way for a dev or more experienced user to troubleshoot. But for the average user, this is a difficult task, especially if Linux is involved. It'd be much easier to just have some sort of health check that simply says this widget is broken so it's getting disabled. In windows, it crashes Kodi with broken widgets (for me). Tracking it down last time was a hassle

**Comment by drinfernoo** [comment]
@BinaryAssault While I find it unlikely that a "broken widget" would crash out of Kodi, there are already certain situations where a completely failed widget will simply "fall out" or show a "broken" indicator.

In an upcoming release (likely 3.4.0), we'll also have a bit more informative "error", "empty", and "loading" tiles, which should give an idea if the overall state of the widget. In their current state (in development), they indicate the widget ID they correspond with, which should hopefully be helpful in tracking things down.
