### ISSUE TITLE
[Bug] Regarding autowidget shortcuts

### ISSUE THREAD

**Issue by rizreflects** [drinfernoo/plugin.program.autowidget#104]
I dont know whether this is a bug or a feature request so I just labelled it as a bug (hope that's okay). Anyway this is the problem I'm having. I created a shortcut group consisting of items in my seren liked movie list. I then renamed this list to 'genres' and this is what it looks like now:

![autowidgetgenres](https://user-images.githubusercontent.com/76912707/129212639-0e2b29b8-46a2-4b29-aa7c-a9880831184f.png)

The problem that i'm having is, when clicking on a shortcut, instead of opening the list directly, this pops up instead:

![autowidgetgenresclick](https://user-images.githubusercontent.com/76912707/129212823-e8aed975-e188-4103-97b1-ed2e9bd947a1.png)

If I click 'Play' the list will open like normal and function properly. However, What I'm asking is, would it possible to open the list directly with one click rather than seeing this extra page?

**Comment by drinfernoo** [comment]
I believe this is because you've set your default action as "Show Information"... Why not use it as a widget?

**Comment by rizreflects** [comment]
> I believe this is because you've set your default action as "Show Information"... Why not use it as a widget?

Oh believe me I have plenty of autowidgets 😂. I actually have widgets for all of those shortcuts cycling (just over 120 alltogether). 

The thing is, I wanted to create a submenu called 'genres' so I can access the lists more easily (rather than waiting for a particular widget to load).

You're right though, I do have show info set in settings.. the problem is if I change that to 'play' the widgets on my homescreen won't show movie information.

Is there no way around this then? It's not a super big problem, I can live with it.. it's just in the past I used superfavourites and that didn't seem to have this problem. It would open the lists directly. The problem is autowidget is simply way more reliable than superfavourites IMO.

**Comment by drinfernoo** [comment]
So is this a shortcut group, or a widget group?

**Comment by rizreflects** [comment]
> So is this a shortcut group, or a widget group?

A shortcut group.

**Comment by drinfernoo** [comment]
You know, I think this probably has to do with the folder logic of the items in the menu... I'll keep it in mind.
