### ISSUE TITLE
[Bug] Group files will not automatically update

### ISSUE THREAD

**Issue by rizreflects** [drinfernoo/plugin.program.autowidget#105]
I've come across quite a problematic bug i'd like to bring to your attention. Any group file that contains a trakt list (in my case via seren) will not update automatically if new movies are added / deleted. The only way for the list to update is by manually clearing the cache in autowidget settings. 

**Details:**
  - What version of Kodi? 19
  - What device? I have tested this on windows, Nvidia shield and the Beelink GT King (running CoreELEC).

I tested this by simply adding a movie to one of my trakt lists and seeing if autowidget would update. On CoreELEC I waited 2 weeks and the list still had not refreshed. I then cleared the cache and the list updated properly.

I feel a good solution to this would be an option in settings to automatically clear the cache after a set time (I would personally set it monthly).

**Comment by drinfernoo** [comment]
The cache should be being refreshed every five minutes or so, but it seems there is an issue with that in the latest stable builds.

Can you please test 0.0.1444 from the devrepo to see if that works better for you? That release contains a lot of fixes and improvements for caching, that should be in stable once we get #98 merged.

**Comment by rizreflects** [comment]
No problem. I'll test it today at some point and get back to you.

**Comment by rizreflects** [comment]
Update: the dev repo is working perfectly. It updates in a matter of seconds. (Tested on Nvidia shield)
