### ISSUE TITLE
[Bug] Background Update message

### ISSUE THREAD

**Issue by luckylukz02** [drinfernoo/plugin.program.autowidget#110]
When I launch Kodi I get a long Autowidget update message displayed on the top right corner. This is fine as I need the update to happen. 

However in my TV show section i get a constant message regarding Autowidget update. At the moment it notifys 33% 66% 0% then repeats.

My question is can this be performed in the background with no message displayed.

This is also messing with my TV lights as you can see here the message  creates a dark area on the top right corner which in turn dims the light.

![20210913_000240](https://user-images.githubusercontent.com/80491975/133005649-99024bd0-1fc0-48c0-a5c0-d7ee5a6cbf12.jpg)

![20210913_000237](https://user-images.githubusercontent.com/80491975/133005655-1409c922-6623-4466-a454-992ee84beb71.jpg)

I was unable to capture the difference that well but in person it is very noticeable.

Thank you

**Comment by drinfernoo** [comment]
Is that notification displaying "constantly", as in it never goes away, or it shows up every few minutes? It really shouldn't be constant...

**Comment by luckylukz02** [comment]
Yes this is constant in TV show section only.

**Comment by luckylukz02** [comment]
Also just to add about #109 also using cosmic skin

**Comment by drinfernoo** [comment]
@luckylukz02 That's not how Kodi works. Widgets load no matter which section you're on. 

What about #109?

**Comment by luckylukz02** [comment]
I don't know how kodi works but in this case it is doing exactly that.

**Comment by drinfernoo** [comment]
In 3.4.2, I've removed the notification.

**Comment by luckylukz02** [comment]
Perfect thank you
