### ISSUE TITLE
[Bug] Shortcuts within a Shortcut crashing Kodi

### ISSUE THREAD

**Issue by tatkodi** [drinfernoo/plugin.program.autowidget#111]
### DESCRIPTION:
I've added a few search shortcuts (e.g. search movies), which contain search paths from different addons to a parent shortcut 'Search', which can be called from home. The parent shortcut is not a widget but it's set as an action to a main menu item.
I have other groups for home widgets too but whenever I use any search shortcut and return to home, Kodi crashes.

### DETAILS
  - Version: **Kodi 19.1**
  - Skin: **Arctic Zephyr 2 Resurrection Mod**
  - Device: **PC**
  - Platform: **Windows 10 x64**

### Log:
https://paste.kodi.tv/udiwucuhas.kodi

**Comment by drinfernoo** [comment]
Your log is far from complete, and doesn't appear to even show a shortcut group being triggered at all.

In order to diagnose this, I'll probably need to see your `.group` files... I presume you mean you're adding the "Search Movies" item from an add-on (for example) to a shortcut group called "Search", such that you end up with a single shortcut group that contains multiple "Search" paths.

I have done the same thing, and set a skin shortcut (in Arctic Horizon) to the shortcut group. Opening any of those shortcuts takes me directly to where they're supposed to go, and doesn't ever end up crashing Kodi.

**Comment by tatkodi** [comment]
### COMPLETE LOG:
https://paste.kodi.tv/olulawirep.kodi

### GROUP FILES:
https://www.dropbox.com/s/fvh3b0fdg9cc0dz/AW%20backup.zip?dl=1

For what I've done is that I've added multiple "Search" items from different movie related add-ons to a "Search Movies" shortcut. I have "Search Anime", "Search Live TV" etc. similarly with multiple search paths in each. Then I added all of these categorized searching shortcuts, like Search Movies, Search Anime etc, to a parent shortcut named "Search".

What I've also noticed that it doesn't always crash but it's happening pretty often, like a lot.

**Comment by drinfernoo** [comment]
Right, so "nested" shortcut groups is what we're looking at.

I'll have to have at this at some point, as I don't think that I've ever tried it myself... But it may be a bit, as I've been fairly busy recently.

**Comment by tatkodi** [comment]
It navigates, searches, and plays content perfectly. The problem is when returning home, it crashes.
I guess I'll just add 4 different widgets to a main menu item.

**Comment by tatkodi** [comment]
I thought removing nested shortcuts would fix the crashing but after that, the circumstances have changed although the crashing is persistent.
The widgets and shortcuts work fine but when I open the AutoWidget add-on for configuration and then return to home, it often crashes Kodi. 

**LOG**
https://paste.kodi.tv/olupomenuj.kodi

**GROUP FILES**
https://www.dropbox.com/s/fvh3b0fdg9cc0dz/AW%20backup.zip?dl=1

**Comment by drinfernoo** [comment]
I don't really think this is an AutoWidget issue... I think this is a Kodi issue, where sometimes returning to the homescreen crashes the program. I've seen it before, and it still happens now and then.
