### ISSUE TITLE
Cant point the widget I’m new to this

### ISSUE THREAD

**Issue by Arthur1967** [drinfernoo/plugin.program.autowidget#112]
Hello I can't seem to point a widget I am using xonfluence I'm 19.1 with an android box it says I have one active widget however I did that I wish I could remember but it seems to be updating them sorry for the novice question but I really want to use this thank you and what is the proper configuration have a good night￼￼￼

**Comment by drinfernoo** [comment]
For Confluence-based skins (like Xonfluence), you need to add the "Cycling"/"Static"/"Merged" option to your Favorites first, then use the skin widget setup in order to use that Favorite as a widget, if my memory serves.

**Comment by Arthur1967** [comment]
I knew it was a simple fix thank you very much have a good night
