### ISSUE TITLE
Which two you

### ISSUE THREAD

**Issue by Arthur1967** [drinfernoo/plugin.program.autowidget#115]
I have a Trakt list of recent released movies￼ Would I use merged static or cycle for this as it updates I'm just not sure thank you sorry for the easy question for you but I did get widgets to initialize it works great￼

**Comment by drinfernoo** [comment]
https://github.com/drinfernoo/plugin.program.autowidget/wiki/How-to-Use-AutoWidget

**Comment by Arthur1967** [comment]
OK thank you
