### ISSUE TITLE
"trying to load setting definitions from old format..." bug dropped connection?[Bug]

### ISSUE THREAD

**Issue by jojobrogess** [drinfernoo/plugin.program.autowidget#120]
### LOGS AT BOTTOM
*****************************************************************************************************************************************

**Describe the bug**
Yeah so I can't really be clear on if this was autowidget or something going on in my network, but this is not the first time I have noticed this happening. 

As I was watching a TV Show, playback started to buffer here and there and then finally gave out stopping playback entirely. 
So I checked my logs and all I see are autowidget nofitications `trying to load setting definitions from old format...`
I have `Path Refreshing` set to `While Nothing Playing` so nothing should be trying to load.

*****************************************************************************************************************************************

**Details:**
  - What version of Kodi? **19.3** **AutoWidget 3.4.2**
  - What skin is being used? **AuraMod**
  - What device? (PC, Smartphone, Fire TV, Nvidia Shield, etc...) **PC**
  - What platform? (Android, iOS, Windows, OS X, Linux, etc...) **Windows 10** (with smb share from rpi 4) 

*****************************************************************************************************************************************

**Additional context**

I have `Path Refreshing` set to `While Nothing Playing`. So it shouldn't be updating while something is playing.
I also have `Widget Refresh Time` set to the max: `12 Hours` because I have for the most part, a static library. 

Logs are pretty verbose, I guess I messed with those settings somewhere(multiple addons it looks like) and so the autowidget hiccup is a little deep:
Logs:
[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/7798554/kodi.log)
>2022-01-01 20:01:33.644 T:9484     INFO <general>: plugin.program.autowidget: Dequeued cache update: 67e81
>2022-01-01 20:01:33.879 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:33.883 T:9484     INFO <general>: plugin.program.autowidget: Wrote cache 30244B (exp:0:03:44, last:1:33:01): >67e81 ['8298a4fd-fb93-404a-a3f5-257dadb28e29', None]
>2022-01-01 20:01:33.906 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:33.908 T:9484     INFO <general>: plugin.program.autowidget: Dequeued cache update: 07de8
>2022-01-01 20:01:34.032 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:34.034 T:9484     INFO <general>: plugin.program.autowidget: Wrote cache 17176B (exp:0:03:44, last:1:33:01): >07de8 ['8565d28c-fcd1-4f0e-b182-ecfc5faa5fc1', None]
>2022-01-01 20:01:34.043 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:34.044 T:9484     INFO <general>: plugin.program.autowidget: Dequeued cache update: 3c352
>2022-01-01 20:01:34.198 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:34.200 T:9484    DEBUG <general>: plugin.program.autowidget: avg_dur 3456313s, med_dur 3456313s, >weighted 3456313s, ones 0.00, all [(3456313.037343979, 27)]
>2022-01-01 20:01:34.202 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:34.204 T:9484     INFO <general>: plugin.program.autowidget: Wrote cache 32336B (exp:15 days, 0:01:57, >last:1:33:04): 3c352 ['0407e5ae-c2a1-4855-bbf1-a0bd40a1671a', None, '0b091f56-6833-428b-814f-dc82a6db38c3']
>2022-01-01 20:01:34.221 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:34.224 T:9484     INFO <general>: plugin.program.autowidget: Dequeued cache update: da39a
>2022-01-01 20:01:34.229 T:9484    DEBUG <CAddonSettings[plugin.program.autowidget]>: trying to load setting definitions from old format...
>2022-01-01 20:01:34.230 T:9484     INFO <general>: plugin.program.autowidget: Error cache 0B (exp:-1 day, 23:59:40, last:39 days, >21:06:47): da39a [None]
>2022-01-01 20:01:34.296 T:5828    DEBUG <general>: ffmpeg[0x22ec9353680X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
>2022-01-01 20:01:34.337 T:4676    DEBUG <general>: ffmpeg[0x22ec934f390X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
>

**Comment by drinfernoo** [comment]
The `trying to load setting definitions from old format...` message is relatively normal. This occurs for a lot of add-ons in your log, and is not an indication of an error.

The log snippet you attached is also normal. AutoWidget performs some background caching in order to make sure that its widgets show the most accurate items quickly.
