### ISSUE TITLE
[Bug] Cannot directly play items in Shortcut Group

### ISSUE THREAD

**Issue by stvg88** [drinfernoo/plugin.program.autowidget#122]
**Describe the bug**
I have a folder containing a list of channels that once I click on it, it will play the channel directly. But this folder contains a lot of channels, and I want to create a Shortcut Group for a subset of these channels so that I can access them from home screen. But once I add the channels to the Shortcut Group, I cannot play them from AutoWidget (I can still play them from the original folder, or even from Favorites if I add the channel to Favorites).
Shortcut Group still behaves as expected if the item is a folder instead (in this case, clicking the item would open the folder).

**To Reproduce**
1.  Create a new Shortcut Group called "Sports"
2.  Go to my IPTV folder, add some channels to "Sports" Shortcut Group using "Add to AutoWidget Group" function in context menu
3.  Go to "Sports" Shortcut Group in AutoWidget
4.  Play any of the shortcut in this group
5.  Result: nothing happens, no error, not loading the channel at all

**Expected behavior**
Channel can be played directly from AutoWidget Shortcut Group

**Screenshots**

**Details:**
  - What version of Kodi? 19.3
  - What skin is being used? Arctic Zephyr 2
  - What device? (PC, Smartphone, Fire TV, Nvidia Shield, etc...) PC
  - What platform? (Android, iOS, Windows, OS X, Linux, etc...) Windows

**Additional context**

**Comment by drinfernoo** [comment]
I've gotten similar reports in the past... unfortunately, I don't have any IPTV service to try and replicate this myself.

If you could upload an AutoWidget backup (from AutoWidget's settings), I may be able to come up with a solution.

**Comment by stvg88** [comment]
[stvg88_backup.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/8007532/stvg88_backup.zip)

Attached the backup here. The Shortcut Group with the issue is called Sports.

In this group, only the 2 shortcuts starting with Bimozie work (because they're actually shortcuts to a folder). The rest can't play.

![image](https://user-images.githubusercontent.com/20413268/152631829-ff42e473-a463-416b-a18b-4d2441d3e863.png)

**Comment by drinfernoo** [comment]
Unfortunately, I don't really have a good way of investigating this one... I don't have (nor know where to get) any of the add-ons that your shortcuts are pointed to.

**Comment by stvg88** [comment]
file manager link: `http://repo.kodi.vn`
repo zip file name: `repository.vmfmatrix-1.0.2.zip`
addon name: `Video Addons > VN Media`

Directory inside addon: `Thể Thao > Sport IPTV > World Poker Tour (1080p)`

Hope this could help you investigate~

**Comment by drinfernoo** [comment]
There is no "World Poker Tour (1080p)" item in that add-on at the moment...

I tried the various shortcuts in the groups you sent, and can replicate this, but I think it's more of an issue with that add-on. AutoWidget can certainly play items directly from a shortcut group, if the add-on the shortcut comes from works correctly.

I believe the issue here is with `setResolvedURL`... but I don't have a very good way of telling if the "shortcutted" add-on will use (or has used) that in its processing, so I don't have a great way of handling this instance.

I'm going to leave this one open, but I'm not sure I'll be able to figure it out in the long term.

**Comment by stvg88** [comment]
Thanks for your effort!

However, if I favorite the channel, then I can play it directly in Favorites. I take it that AutoWidget implements the shortcut differently from Kodi's native Favorites function?

**Comment by drinfernoo** [comment]
@stvg88 Yes, it's completely different.

**Comment by stvg88** [comment]
hi @drinfernoo just fyi, i tried using Super Favorites add on from this repo https://github.com/jmooremcc/Repository.jmooremcc/raw/master/jmooremcc.repo.zip , and it's able to play the channels above! Not sure whether that add on has the same implementation as Kodi's native Favorites function or not, but you can take a look if you want!

**Comment by drinfernoo** [comment]
I've had an idea, but haven't had time to test it thoroughly yet.

**Comment by drinfernoo** [comment]
@stvg88 Can you try 0.0.1526 from the devrepo? You'll need to add your shortcuts again (I'd recommend removing the old ones first to mitigate confusion, or just make a new group for them), but I've made a fix that *may* help. It doesn't work for **everything** I tested, but for most reasonable add-ons, it seems to work.

**Comment by drinfernoo** [comment]
@stvg88 Is this fix working for you?

**Comment by stvg88** [comment]
@drinfernoo sorry haven't got the chance to test yet since i'm overseas for awhile and didn't bring my kodi setup with me 😅 will update once i got the chance to test!

**Comment by drinfernoo** [comment]
Pretty sure this should be working now, as of 3.6.1 👍

**Comment by stvg88** [comment]
@drinfernoo hi just managed to test this. It can be played directly from AutoWidget now, but kodi would crash if I put the AutoWidget group as a home screen widget. I suspect that could be due to the skin I'm using though (cosmic) 😂
