### ISSUE TITLE
paged widgets not updating[Bug]

### ISSUE THREAD

**Issue by daveftw84** [drinfernoo/plugin.program.autowidget#124]
when i click next page, the widget isnt updating to show the next items with aura mod and imdb helper.
i have show next page enabled and widget limit set to unlimted.
when i click next page, nothing happens unless i refresh skin

**Comment by drinfernoo** [comment]
Are you clicking on "Next Page" from AutoWidget, or "Show More" from AuraMOD?

**Comment by daveftw84** [comment]
from autowidget, i tried show more for giggles but that loads me into a new menu away from home

**Comment by daveftw84** [comment]
i think it looks like skin isnt being updated to show changes. when i force skin refresh i see things have moved in the widget

**Comment by daveftw84** [comment]
skin needs aggressive widget updating, which it doesnt have
