### ISSUE TITLE
Error to Clear Cache

### ISSUE THREAD

**Issue by gtkingbuild** [drinfernoo/plugin.program.autowidget#127]
In the latest version of Autowidget it gives a registration error again when using the "cache cleanup" tool in the settings

**To Reproduce**
1.  Go to 'Tools'
2.  Click on 'Clear Cache'
3.  Click on 'Yes'
4.  See error

**Details:**
  - What version of Kodi? Kodi 19
  - What skin is being used? AuraMod by SerpentDrago
  - What device? PC
  - What platform? Windows

[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/8399580/kodi.log)

**Comment by drinfernoo** [comment]
Fixed in 3.6.1.
