### ISSUE TITLE
[Bug] - Unable to Use Shortcuts to Playable Files

### ISSUE THREAD

**Issue by phlvdf** [drinfernoo/plugin.program.autowidget#13]
AutoWidget - Shortcut groups: live channels not working

I’ve created a shortcut group that points to selected live streams from different addons. For some reason, they don’t work from the AutoWidget shortcut group (but they all work if I access them from the addons themselves).

Here’s a log (my apologies if it’s too long, it’s my first time creating one):
https://paste.ubuntu.com/p/YMDCbHbQWy/

The apps I’m trying to get the live streams from are:

1) plugin.video.raitv-master.zip
2) plugin.video.mediasetplay-master.zip
3) plugin.video.rivedila7-master.zip

(They can all be downloaded from the Android Aba repo: https://androidaba.com/addons)

**Comment by drinfernoo** [comment]
I believe I've narrowed this down to the fact that those are *playable* "files". I should have a fix soon that allows these to work, as well as direct shortcuts to other playable files as well.

**Comment by drinfernoo** [comment]
Will you attempt to use these in `1.5.0`? You shouldn't even need to change your groups. Simply update the add-on, and see if your existing shortcuts work.

**Comment by phlvdf** [comment]
I’ve tried a few times, but it always crashes while loading and then exits Kodi (I use a Shield, if it helps...)

**Comment by drinfernoo** [comment]
@phlvdf I'll need a debug log.

**Comment by phlvdf** [comment]
Of course, here it is: https://paste.ubuntu.com/p/nCVQsWrpZW/

One more thing I’ve experience after the update, and I hope it is reflected in the log, is that when I now try to edit the icon path of my shortcuts it returns an error.

**Comment by drinfernoo** [comment]
It looks like to me that the shortcut ia working, but the YouTube add-on is what's crashing it.

The error with artwork is a separate issue, but I haven't seen what the error actually is yet 😅

**Comment by phlvdf** [comment]
I’ve tried opening the shortcut from the addon itself (instead than from the homepage) and it works. I’m confused as to why YouTube sticks its nose in it if I’m trying to click on the shortcut from the homepage... If you have any suggestion, it will be very welcome!

Also, I’ve just got a log for the icon issue, would you like me to open a new issue, or should I just attach it here?

**Comment by drinfernoo** [comment]
A new issue would be great 👌 I'll look into this one a bit further this evening, but that does sound like it might be something on YouTube's end.

If you could attach your group file, that would help me out.

**Comment by drinfernoo** [comment]
Ok, so I've figured out the *issue*... but not the fix.

For some reason, the YouTube add-on doesn't like to have it's paths called by `PlayMedia(...)`, but only when called from a widget. I'm really not sure why that would be, but I haven't seen any other add-ons have this issue (yet).

It's possible that something is being handled incorrectly on my end though, as running those same paths with `RunPlugin(...)` *does* work. Either I'll have to figure out a more appropriate method of deciding which command to call, or add special handling for YouTube.

**Comment by drinfernoo** [comment]
For the time being, I've just added an exclusion for YouTube paths. It'll work fine, and allow me a sort of "whitelist" for future add-ons that may behave similarly.
