### ISSUE TITLE
[Request] Muti-row paged widgets

### ISSUE THREAD

**Issue by Mr-7mdan** [drinfernoo/plugin.program.autowidget#134]
Although i think, this is a skin-feature, but in your video on youtube (https://youtu.be/Kf8BiKJy46o), you’ve done a multirow widget as a presentation for an upcoming feature in autowidget

I am not sure if this is an Autowidget feature or it is Arctic Horizon. 

Pls help start digging on this. I cannot seem to find where to start

thanks

**Comment by drinfernoo** [comment]
That is the `icon` widget aspect in Arctic Horizon.

**Comment by Mr-7mdan** [comment]
I used to use AH and now i use AH2. The icon aspect doesn’t wrap/extend to a second row. Only one row appears.
I just check AH. I can confirm that it is one row inside the widget using the icon aspect
