### ISSUE TITLE
[Bug] Unable to edit shortcut icons/thumbs

### ISSUE THREAD

**Issue by phlvdf** [drinfernoo/plugin.program.autowidget#14]
With the new update I’m having troubles editing the shortcuts icons: I click on Edith path / Art / and then I get an error message inviting me to check the log.

Here is a log: https://paste.ubuntu.com/p/NzQS6fd8Mj/

I hope this provides enough context, I’ll be happy to gather more info if necessary.

**Comment by drinfernoo** [comment]
This *should* be fixed in version 0.0.624 from the devrepo... but if you'd confirm (or someone else), I'll push it to the stable repo as well.

**Comment by phlvdf** [comment]
I have downloaded the dev version, and have opened it to try to edit the artwork from there but unfortunately had the same error message. 

Here’s the log: https://paste.ubuntu.com/p/NGN82gf9RM/

**Comment by drinfernoo** [comment]
Your log still shows `1.5.0`. Make sure that you install `0.0.624` from the devrepo.

**Comment by phlvdf** [comment]
I did, and I have opened that one to edit the thumbs... should I perhaps delete 1.5.0. and open 0.0.624 only after I did that? 

I’m still pretty “new” to this, please feel free to give me pointers.

**Comment by drinfernoo** [comment]
Hmm, it may be best to uninstall the add-on first, yeah. Then when you install, it will give you a long list of options.

**Comment by phlvdf** [comment]
Before I do that: if I do so, will I loose all my shortcuts and widgets?
If so, I will download it to a different device. What do you reckon?

**Comment by drinfernoo** [comment]
I reckon, go ahead and update to `1.5.1`. I tested it myself and it should be working fine now.

**Comment by phlvdf** [comment]
Thank you!
