### ISSUE TITLE
Can't install autowidget on fresh install

### ISSUE THREAD

**Issue by NedMitch** [drinfernoo/plugin.program.autowidget#141]
Hi, I have got a fresh build of Kodi 18.9 on an Android note 20 as well as a Chromecast with Google TV. When it comes installing the latest version via your repo of autowidget, it fails during the installation and I have tried several versions of the add-on. 
Any ideas what might be causing this?

![Screenshot_20220923_000914](https://user-images.githubusercontent.com/114031205/191867103-906cd1cd-6d3a-4816-ba9f-b723d83a09f9.jpg)

Clearly seems to be about a queue module missing but I'm not sure how to fix it...

Thanks for your help

**Comment by dmyoung9** [comment]
Ohh... looks like this was broken in #108. @djay, looks like `queue` is not valid in Python 2.7 😬

**Comment by djay** [comment]
It's not meant to be python 2.7 compatible. Upgrade to Kodi 19
