### ISSUE TITLE
[Bug] Error after updating from 1.45 to 1.50,1.51,1.52

### ISSUE THREAD

**Issue by papadcha** [drinfernoo/plugin.program.autowidget#15]
**Describe the bug**
I created as described in your youtube video some widgets with version 1.45 when the 1.50 version was available and updated the same widgets I get error that prompt me to check error log. Same error appear also with 1.51 and 1.52. When I downgrade to 1.45 everything works fine. I uninstall the autowidget and clear the usedata folder of addon (also before I was purge data from tools menu of the widget and installed a fresh 1.51 version of autowidget. Same error. Downgrade again to 1.45 everything works ok.

[errorlog.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/4530751/errorlog.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details:**
 - What version of Kodi? 18.6
 - What skin is being used? auramod
 - What device? Mibox3
 - What platform? Android

**Additional context**

[errorlog.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/4530783/errorlog.txt)

**Comment by drinfernoo** [comment]
Can you please zip your `addon_data/plugin.program.autowidget` folder, and attach it here? That way I can replicate your exact situation.

**Comment by papadcha** [comment]
Done, file uploaded. And thanks for quick response. BTW neither 1.53 fix my error.
[plugin.program.autowidget.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/4531604/plugin.program.autowidget.zip)

**Comment by drinfernoo** [comment]
Actually, I think the issue appears to be that you have more widgets defined that paths in your group. Is that right? It would look like three widgets all pulling from the "Movies" group.

Due to recent changes in the way I avoid having the same path onscreen from two different AutoWidgets, I think that would cause this.

I'll have to look further into it. 

EDIT: I would presume that adding a third path to the group would stop the error.

**Comment by papadcha** [comment]
For your help. I delete addondata folder of your addon. (I dont know how the path from version 1.45 pointing to spotlight remains because I was delete it as I previous said), I upgrade to 1.53 latest version. Add only one group with only one widget. Same error. The plugin dont even initialize the widget.

**Comment by drinfernoo** [comment]
This should be fixed in `1.5.4`.
