### ISSUE TITLE
[Request] Hide Notifications During Playback

### ISSUE THREAD

**Issue by Demonseeed** [drinfernoo/plugin.program.autowidget#2]
Hi drinfernoo, great work on this addon!

I just wanted to see if there is a way to disable notifications (namely, the widgets refreshing notification) during playback?

I think possibly a setting with three options:
Notifications:
- always
- none during playback
- never

Thanks again!

**Comment by drinfernoo** [comment]
There may be a way, but I hadn't thought of it. I actually really like seeing the little notification and knowing there will be new lists when I'm done watching what I'm watching... But it could be done, probably 👍

**Comment by Demonseeed** [comment]
Thank you my friend!

I personally also do not mind it, however le wife does 😂

**Comment by drinfernoo** [comment]
I have recently added a setting to disable the notification completely. Does that work, or would you still prefer the ability to show it unless something is playing?

**Comment by drinfernoo** [comment]
@Demonseeed, I'll be implementing it as you suggested in the beginning: https://forum.kodi.tv/showthread.php?tid=352934&pid=2935517#pid2935517
