### ISSUE TITLE
[Request] Backup option for My Groups

### ISSUE THREAD

**Issue by dinkysniff** [drinfernoo/plugin.program.autowidget#27]
**Is your feature request related to a problem? Please describe.**
No, not related to a problem.

**Describe the solution you'd like**
An option to create a backup / restore for My Groups within the add-on. Useful for users that would like to copy their groups over multiple devices

**Describe alternatives you've considered**
Currently can replicate through a copy of the folder, and paste to second device.

**Additional context**
Simple option to save via a network drive would be neat.

**Comment by drinfernoo** [comment]
In doing this, I would allow to choose a backup location, which could be set as a network location. I'd also like this to include a restore function as well, which would function similarly.

The main issue I see with this is one of confusion, once people realize that backing up their groups won't back up the widgets they've set. Unfortunately, that's a bit too out of the scope of AutoWidget, I think, but would be something a "theme" backup from OpenWizard could be useful for.

**Comment by dinkysniff** [comment]
Is it possible to have a pop up menu with a reminder that it won't back up user lists/feeds prior to backup?

**Comment by drinfernoo** [comment]
Definitely. Having done it myself, dropping group files into an existing install works just fine, as long as all the paths are valid *in* that install (folders which require authorization, add-ons not installed, etc...). The only thing that won't get backed up easily are the actual widgets that are set in the skin at the time of backup.
