### ISSUE TITLE
[Bug] widgets from single add-on crashes

### ISSUE THREAD

**Issue by Xaque8787** [drinfernoo/plugin.program.autowidget#30]
**Describe the bug**
Kodi crashes when selecting widget item if there a multiple sources from the same addon in autowidget folder.

**To Reproduce**

When adding sources from one add-on and using them as a home screen widget causes Kodi to crash. This issue also occures when setup using super favorites so it maybe a Kodi issue not add-on specific.

Example: using auto widget I created a folder that contains my links for the browser launcher add-on. Then added this folder as home screen widget. Kodi crashes upon selecting widget item.

**Expected behavior**
Not able to use auto widget folder containing multiple sources as home scrwen widget without crash.

**Screenshots**

**Details:**
 - What version of Kodi? Lelia 18.6
 - What skin is being used? Arctic zephr 2
 - What device? PC
 - What platform? Windows10

**Additional context**
Additional searching about issue I found that others have had this problem as well and have just found alternative work around, none of which satisfy me. This issue occuring with the super favorites add-on as well has a kodi forum post about the add-on not being supported anymore, and thus the reason no fix has been updated. Some posts about changing the player.py file to get it to work, but not enough info for me to go off of. Hoping the author of this add-on can help.

**Comment by drinfernoo** [comment]
I'm actually thinking this would be an issue with the actual paths themselves, and how they're called. Is this a shortcut group? Can you get me a log file of the error? When you say "crash", do you mean an error inside Kodi, or Kodi closes completely?

I can confirm that the issue doesn't have to do with using one add-on per group, as I have many groups comprised of multiple paths from a single add-on.

**Comment by Xaque8787** [comment]
Kodi crashes with no error. The paths for the sources are not shortcuts, they are from the add-on (browser launcher). Everything works until I select an item from the widget on the home screen.

Created a multiple links to websites in browser launcher add-on. Added each link to autowidget group, called that group as widget from skin. Go-to homescreen, select item from said widget, Kodi then crashes.

**Comment by Xaque8787** [comment]
Reproduced issue on different machine. Like you said maybe an issue with it being a shortcut group. I have no other option when creating a autowidget group to choose something other than shortcut. In the advanced setting when editing a group or source I can manually change that value, but I can't find any documentation on advanced setting commands.

Here is the crashlog and error log for issue.
[Crashlog.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/4647714/Crashlog.zip)

**Comment by drinfernoo** [comment]
Can you also share the `streaming_services-1589843888.07.group` file from AutoWidget's addon_data folder?

**Comment by Xaque8787** [comment]
Here you go sir, and thank you for your time.
[streaming_services-1589843888.07.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/4647866/streaming_services-1589843888.07.zip)

**Comment by drinfernoo** [comment]
@Xaque8787 Can you try the latest devrepo release?

**Comment by Xaque8787** [comment]
Tested the dev repo and it is now working. You sir are a dedicated dev and I applaud your devotion. Got a patreon or way do donate? I'd like to buy you a beer.

**Comment by drinfernoo** [comment]
In my case, "devotion" is more like "obsession" 😅

I don't, but that's ok. I appreciate it all the same 👍
