### ISSUE TITLE
[Bug] Fanart doesn't display on certain widgets

### ISSUE THREAD

**Issue by skyfsza** [drinfernoo/plugin.program.autowidget#36]
Fanart is blank on widgets when added from autowidget.

**To Reproduce**
1. Create group with folders from Netflix Addon
2. Add random path from group as a home widget
3. Check fanart background for movie/tv shows on the home widget (seems to apply only to movies/shows without fanart already in cache).

**Comment by drinfernoo** [comment]
I cannot reproduce this with the current devrepo changes... I added three different paths into a group, and created two random widgets. I have what appears to be full artwork on them all, including `clearlogo` (but unfortunately not `clearart` 😅).

It does seem that the widget needs to actually *display* `fanart` first, from my initial testing. So, for example: I had widgets set to "show landscape art", and they did, but the backdrop didn't show `fanart` until I turned off that setting, allowing the widget to load that art instead.

Regarding this, it seems like more of a skin issue, in my opinion...

An item (chosen at random) from the Netflix add-on returns me the following artwork in the JSON-RPC response:
```json
{
  "fanart": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2f9pS1daC2n6UGc3dUogvWIPMR_OU%2fAAAABUDsrSAiKh_XjTLGCMMBd6EgVYR0WCnfEiqdbTcqVEbusV_6CG_qBI9O0TDv1xjVClCG1LgGrTesgQesyxWsYOOm19sbkLFG65-FnM8tQZwZjVWtbA.jpg%3fr%3df42/",
  "poster": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fevlCitJPPCVCry0BZlEFb5-QjKc%2fAAAABQUHSxrPtgo4FkPFO4P39JPwA75sp1E_Do_NKgUQxJ_qWO1d90vJLuHVkEyy0j3MfNGNRLaboHb7WLTfZRSQhWZ9jHt6-K27B1qDjPb9vGXq2evzSi0X6PY5kwm7Gw.jpg%3fr%3dd59/",
  "thumb": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fX194eJsgWBDE2aQbaNdmCXGUP-Y%2fAAAABbmvO7dIQL9Jkhu3OVQLiZFQW_5VQwqs4udWWGtlfIbOvggIwEVxUTBU2sUJVhBje3R35TEoHHXLg09MEVZX7Kx5HnaizV8hWgQz_7EkSwy6jwCq4JbNsv85u0-fIA.jpg%3fr%3db92/",
  "landscape": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fX194eJsgWBDE2aQbaNdmCXGUP-Y%2fAAAABbmvO7dIQL9Jkhu3OVQLiZFQW_5VQwqs4udWWGtlfIbOvggIwEVxUTBU2sUJVhBje3R35TEoHHXLg09MEVZX7Kx5HnaizV8hWgQz_7EkSwy6jwCq4JbNsv85u0-fIA.jpg%3fr%3db92/",
  "clearlogo": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fH8D6qtacWfxpwORI6dw3sYdASQc%2fAAAABSP8qAsB_vCg09p18aNYLD3fJs9EzVc6SWQlb_CA3CpDjKEsw0XdN3o4B5bHRLG0XtrgkxcMuoD31pdYeat2t07GmuWzhZIbxWOFbNh0bunQ0Wy8gHcAersjC5y7TE3mutqcAZLk2wNUPiLK8gDLQy45OC1W133n3Bc9GYKn3Qs.png%3fr%3dc36/"
}
```
And that artwork is set directly to each AutoWidget item, with no modification to their value or structure, on line 353: https://github.com/drinfernoo/plugin.program.autowidget/blob/f4dd655714be9b44c26153e07fe3b0c7e9cdb182/plugin.program.autowidget/resources/lib/menu.py#L351-L356

I'm open to investigating this further if something really isn't working out for you, but on my end it appears to be working in Arctic Zephyr 2 and Arctic Horizon, at the least.

**Comment by skyfsza** [comment]
> I cannot reproduce this with the current devrepo changes... I added three different paths into a group, and created two random widgets. I have what appears to be full artwork on them all, including `clearlogo` (but unfortunately not `clearart` 😅).
> 
> It does seem that the widget needs to actually _display_ `fanart` first, from my initial testing. So, for example: I had widgets set to "show landscape art", and they did, but the backdrop didn't show `fanart` until I turned off that setting, allowing the widget to load that art instead.
>
My issue is related to fanart backdrop, not the artwork on the widget itself, so I dont see how the switch to "show landscape art" would have any effect (that simply tells the skin to use landscape instead of thumb/fanart on the widget).

> Regarding this, it seems like more of a skin issue, in my opinion...
> 
> An item (chosen at random) from the Netflix add-on returns me the following artwork in the JSON-RPC response:
> 
> ```json
> {
>   "fanart": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2f9pS1daC2n6UGc3dUogvWIPMR_OU%2fAAAABUDsrSAiKh_XjTLGCMMBd6EgVYR0WCnfEiqdbTcqVEbusV_6CG_qBI9O0TDv1xjVClCG1LgGrTesgQesyxWsYOOm19sbkLFG65-FnM8tQZwZjVWtbA.jpg%3fr%3df42/",
>   "poster": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fevlCitJPPCVCry0BZlEFb5-QjKc%2fAAAABQUHSxrPtgo4FkPFO4P39JPwA75sp1E_Do_NKgUQxJ_qWO1d90vJLuHVkEyy0j3MfNGNRLaboHb7WLTfZRSQhWZ9jHt6-K27B1qDjPb9vGXq2evzSi0X6PY5kwm7Gw.jpg%3fr%3dd59/",
>   "thumb": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fX194eJsgWBDE2aQbaNdmCXGUP-Y%2fAAAABbmvO7dIQL9Jkhu3OVQLiZFQW_5VQwqs4udWWGtlfIbOvggIwEVxUTBU2sUJVhBje3R35TEoHHXLg09MEVZX7Kx5HnaizV8hWgQz_7EkSwy6jwCq4JbNsv85u0-fIA.jpg%3fr%3db92/",
>   "landscape": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fX194eJsgWBDE2aQbaNdmCXGUP-Y%2fAAAABbmvO7dIQL9Jkhu3OVQLiZFQW_5VQwqs4udWWGtlfIbOvggIwEVxUTBU2sUJVhBje3R35TEoHHXLg09MEVZX7Kx5HnaizV8hWgQz_7EkSwy6jwCq4JbNsv85u0-fIA.jpg%3fr%3db92/",
>   "clearlogo": "image://https%3a%2f%2focc-0-1007-1009.1.nflxso.net%2fdnm%2fapi%2fv6%2fH8D6qtacWfxpwORI6dw3sYdASQc%2fAAAABSP8qAsB_vCg09p18aNYLD3fJs9EzVc6SWQlb_CA3CpDjKEsw0XdN3o4B5bHRLG0XtrgkxcMuoD31pdYeat2t07GmuWzhZIbxWOFbNh0bunQ0Wy8gHcAersjC5y7TE3mutqcAZLk2wNUPiLK8gDLQy45OC1W133n3Bc9GYKn3Qs.png%3fr%3dc36/"
> }
> ```
> 
The artwork url is correctly being added to the Infolabel, I can see the url in Devhelper, the issue seems to be Kodi does not load the fanart backdrop with autowidget - unless the fanart is already in cache (accessed the same movie/tvshow direct in the addon previously).

> And that artwork is set directly to each AutoWidget item, with no modification to their value or structure, on line 353:
> 
> https://github.com/drinfernoo/plugin.program.autowidget/blob/f4dd655714be9b44c26153e07fe3b0c7e9cdb182/plugin.program.autowidget/resources/lib/menu.py#L351-L356
> 
> I'm open to investigating this further if something really isn't working out for you, but on my end it appears to be working in Arctic Zephyr 2 and Arctic Horizon, at the least.
