### ISSUE TITLE
Autowidget does not support Adding Movies in Bingie Skin 1.0.3

### ISSUE THREAD

**Issue by ivysashar** [drinfernoo/plugin.program.autowidget#38]
I set up an autowidget group "Popular Movies" and added Popular Movies folders from Exodus and Seren. 

After setting it up in Bingie as a widget with random recycling path, the images are shown in the home page. When I click on Play in the Movie page, instead of playing the movie, it brings me to an empty folder instead.

**Comment by drinfernoo** [comment]
Do you still have this issue?

If so, can you send one of your group files? It sounds like you've made your groups in an unusual or unintended way...
