### ISSUE TITLE
[Enhancement] Support Skins Without Skin Shortcuts Integration

### ISSUE THREAD

**Issue by drinfernoo** [drinfernoo/plugin.program.autowidget#4]
Recently I've realized that skins which *don't* use Skin Shortcuts to manage their menu (as a great number of skins do now) must be able to store "widget" metadata in skin strings... the same way AutoWidget does 🤔

It should be fairly simple with that line of thought, I just had to think of it 😅

**Comment by drinfernoo** [comment]
Possible side effects may include: "future-proofing" against a day when Skin Shortcuts is deprecated, "nested" widget groups (which should theoretically be possible with shortcut groups, now), and potentially universal skin support barring major changes to Kodi core 🙌

**Comment by drinfernoo** [comment]
@jurialmunkey, will Kodi not parse an `$INFO[...]` tag inside of a skin string? 🤔

**Comment by jurialmunkey** [comment]
> 
> 
> @jurialmunkey, will Kodi not parse an `$INFO[...]` tag inside of a skin string? 🤔

As far as I gather, the info is converted immediately into an immutable string, thus removing the `$INFO[...]` as a reference.

e.g. 
consider
`info = {'genre': ['Action']}`

In the skinning engine
`Skin.SetString(foobar,$INFO[ListItem.Genre])`
is equivalent to
`foobar = '{}'.format(info.get('genre'))`
not
`foobar = info.get('genre')`

So if now `info['genre'] = ['Adventure']`
then `print(foobar)` still outputs `['Action']`

**Comment by drinfernoo** [comment]
Interesting... I thought so too. Trying to put a skin string containing a plugin path, wrapped in `$INFO` didn't work in AH's fullscreen widget path 🤔
