### ISSUE TITLE
Launching Android apps from Shortcuts

### ISSUE THREAD

**Issue by sdstreams** [drinfernoo/plugin.program.autowidget#48]
**Describe the bug**
When I save an android app to shortcuts it will not launch the app. Kodi Favourites can launch android apps installed outside of kodi. Would Autowidget soon have this capability?

**To Reproduce**
Program add-ons/back a directory/Android apps. Select any android app and add to autowidget. Shortcut then save to any folder.

**Expected behavior**
when selecting Android app saved to shortcut hoping it would launch the app.

**Details:**
  - What version of Kodi? 18.8
  - What skin is being used? artic zypher leia mod
  - What device? Nvidi Shield
  - What platform? Android

**Comment by drinfernoo** [comment]
Ah, I actually thought this did work 😅 I've fixed it at least once before, but must have broken it again...

What happens when you try to launch it? Could you send the `.group` file containing the shortcut in question?

**Comment by drinfernoo** [comment]
Actually, I've just fixed it! It was some backwards logic in my shortcut parsing 😁

**Comment by sdstreams** [comment]
Awesome! thank you. I thought it might be my device. Loving the app. I tend to use it in place of super favs....autowidget more reliable.

**Comment by drinfernoo** [comment]
@HenioH Honestly, that's great! My original ideas for AutoWidget didn't really have this in mind, but I think it's fair to say it's almost to the point we could replace SF all together 😅
