### ISSUE TITLE
Live TV/Advanced Emulator Launcher  Open Issue/Message

### ISSUE THREAD

**Issue by matth392** [drinfernoo/plugin.program.autowidget#49]
Hi there, first off I want to say thanks so much for the plugin - I'm absolutely loving it with my Arctic Zephyr build; and apologies for opening an issue with very little detail as to what the issue actually is; I am more a less a newbie in terms of programming and also the inner workings of Kodi etc. though know a small amount of Python and a fair amount of fullstack.
However I managed to get Autowidget 2.1 set up and working with both Live TV (Cycling between favourite channel groups as a widget between UK channels and Romanian for myself n the missus.)  But also I had managed to get AutoWidget to launch games from Advanced Emulator Launcher (which I am using as a gaming frontend - they're working fine launching from AEL but something's killed the ability to launch an external program from a widget) Unfortunately both of these now no longer work. Usually I would never message or open an issue but have been playing about with this for the past couple of days and its absolutely doing my head in - If you could point me in the right direction or tell me if I'm being a complete moron I would really really appreciate it. 

P.S. if there's any way at all that I could contribute in terms of development or design etc. I would absolutely love to please let me know

**Comment by drinfernoo** [comment]
First of all, I'd recommend updating to the latest stable release: 2.3.4 at this time.

Aside from that, the most helpful thing you can provide are the corresponding `.group` files, found in `special://userdata/addon_data/plugin.program.autowidget/`. Those should tell me anything "relevant" I may need in order to figure out why they're not working for you anymore.

**Comment by matth392** [comment]
Hi there I'm really sorry for taking so long to respond I honestly didn't expect such a quick response and fell asleep; 
here are the following group files - I am not sure what's actually going on with them honestly because looking at the files themselves though I did notice they're listing the group types as directories; 
 
Once again thank you so much for helping - I really honestly appreciate it so much :) 

[games-1597887412.43.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/5106282/games-1597887412.43.txt)
[live_tv-1597882850.11.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/5106283/live_tv-1597882850.11.txt)

**Comment by drinfernoo** [comment]
So, to be clear, widgets pointed to a cycling path from these groups... show items correctly, but when clicked they do nothing? Is there an error, or simply no effect at all?

**Comment by matth392** [comment]
Yeah that's pretty much bang on what's happening - particularly with the games which is quite strange as it was cycling quite happily two days ago with no problems launching or anything like that - I have tried using a static widget to launch each of the various pathway's and they've launched quite happily; no error message has been logged or anything like that either.

**Comment by drinfernoo** [comment]
@matth392 Have the groups that you sent me been created *since* the time when they worked? It appears those were created using version 2.3.4, but I'm not sure in which version they were working before. 

EDIT: For what it's worth, it's unlikely that cycling vs. static has any beating in the situation. Most likely, it has to do with the logic AW uses to decide how to call the path of the item you click.

**Comment by matth392** [comment]
I did recreate the groups yeah; I was actually following your labelling tutorial and figured it would be best to start from scratch! XD

**Comment by drinfernoo** [comment]
@matth392 Any idea on which version they *did* work? I suspect my only course will be to learn how to set up AEL finally so I can do my own testing 😅

**Comment by matth392** [comment]
One thing that did occur to me as the autosub addon is throwing up an error stating that it can't find a video file; which would suggest that Autowidget is seeing the Roms/Steam Links as video files instead of executables. it was version 2.32 I think; Unfortunately the whole thing just went bang and seems to have disappeared entirely - I am going to reboot and see what's happened  :)

**Comment by matth392** [comment]
So interesting thing - I have rebooted and reinstalled the addon on a basic cycling path for games again - when I try and launch an emulated game it actually directs me to the video folder that the game's in - for steam it just cycles; 
![image](https://user-images.githubusercontent.com/64239430/90845749-9ab1dc80-e35e-11ea-97f9-f4a932bed7ec.png)

**Comment by drinfernoo** [comment]
@matth392 Would you be able to send me an AutoWidget debug log from the latest devrepo release? The release to test is currently 0.0.1039 from the devrepo.

You'll need to enable "Debug Logging" in AutoWidget's settings, and then a file will be generated at `special://userdata/addon_data/plugin.program.autowidget/aw_debug.log`. I've added a few more log statements that should help me narrow down what's happening for you.

**Comment by matth392** [comment]
Once again apologies - as I fell asleep however I have just reset Autowidget once again and it's actually produced an error log this time :) However it wasn't actually an Autowidget error log but the main kodi debug log  I've included it but looking at it  - it doesn't seem to recognise the file types 
[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/5111776/kodi.log)

**Comment by matth392** [comment]
I am so sorry I feel like a complete ,moron I completely misread the part aboput the dev release - I will do that immediately :/

**Comment by matth392** [comment]
[aw_debug.log](https://github.com/drinfernoo/plugin.program.autowidget/files/5111784/aw_debug.log)
Here's the Debug Log :) Thank you again for so patient with me when I'm being such a plonker :)

**Comment by drinfernoo** [comment]
Yeah, I'm afraid I'll have to set one up and see for myself. It seems like everything in your log is as expected 🤔

**Comment by matth392** [comment]
Ah, that ain't great :( Honestly its not that much of an issue for me with everything  - more that it was just a nice convenience and I really honestly do appreciate the help you've given me a huge amount. As I said initially I know bits and pieces of Python and am trying to learn it between work and life in general - I'll continue to read up and see if it comes to anything; If there's anything else I could do to help you or anything at all like that please let me know :)

**Comment by drinfernoo** [comment]
I'm pretty sure this has been fixed and we forgot to close the issue 👍
