### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by ComradeSerg** [drinfernoo/plugin.program.autowidget#50]
Does the autowidget support unicode? I can create group with Cyrillic label, but I can't browse such groups because of error. If I'll change label back to English I then can browse it again.

**Comment by drinfernoo** [comment]
Ahh, I'd love to support that! I've done my best to catch Unicode errors wherever possible, but if you'll shoot me a log, I should be able to fix it 👍

**Comment by ComradeSerg** [comment]
Dude, that was just a question. I thought the creator of the addon could answer whether his product supports unicode without logs. I didn't ask to fix the bug, because I didn't know if it was a bug or it was simply not supported. But if it is impossible to find out without logs, then here they are (I suspect that what interests you is on 2020-08-31 12:00:48.100 T:1322488704):

[kodi_logs.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5149452/kodi_logs.zip)

**Comment by drinfernoo** [comment]
Yes, my addon supports Unicode everywhere possible, except it appears I must've missed a spot 😅 I'll get on it soon 👍

**Comment by drinfernoo** [comment]
@ComradeSerg Could you test version 0.0.1059 from the devrepo? I tested it against a few different situations, but would like confirmation before I merge the fix.

**Comment by ComradeSerg** [comment]
Indeed, the mistakes are gone. At least in the place where I noticed them.
And quick question if you don't mind: is it possible to somehow add the built-in RSS used by the kodi? Unfortunately, when you click on the running RSS line, there is no menu to use AutoWidget, but can this be done manually somehow?

**Comment by drinfernoo** [comment]
@ComradeSerg Good, I'll merge these fixes soon.

Regarding RSS... I don't even know how I would? Is there a manu somewhere where you can see individual items from the feed?

**Comment by ComradeSerg** [comment]
Not sure about menu, but in some skins I saw some manipulation with RSS (changing position, fonts, etc). But it was a quick question, if you don't know, it's okay
