### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [drinfernoo/plugin.program.autowidget#51]
**Describe the bug**
ERROR Getting Plugin://plugin.program.autowidget/?action=static&group=movies...
Autowidget Error, Check Log for more information.

It may be a bug, or an error. Tried to find a solution but none seems to work. Followed drindernoo's Autowidget video of how to create AutoWidgets: https://www.youtube.com/watch?v=lA67gDeaa98

Error keeps appearing when creating a (Random, Static Path). Shortcut's Action is as follows: ActivateWindows(Programs,"plugin://plugin.program.autowidget",return).

I cannot Initialize Widget due to the error.

**To Reproduce**
1.  Go to Edit Skin
2.  Click on 'Customize Main Menu'
3.  Click on 'Widgets'
4.  (Add the autowidget group previously added. eg. Genres Autowidget
4.  When added, the error appears on right top corner

**Details:**
  - What version of kodi? 18.8.0
  - What skin is being used? Arctic Horizon
  - What device? (PC, Smartphone, Fire TV, Nvidia Shield, etc...) PC 
  - What platform? (Android, iOS, Windows, OS X, Linux, etc...) Windows 10 Pro

**Additional context**
Seeking for a solution, or fix

**Comment by drinfernoo** [comment]
I'd need to see the error, from your log file.

**Comment by ghost** [comment]
https://imgur.com/gallery/UVqp6rx There you go.

**Comment by drinfernoo** [comment]
It appears you're using a group file from a legacy (1.x) version of AutoWidget...

You could send `special://userdata/addon_data/plugin.program.autowidget/movies-1599334763.45.group` to verify, but I'm fairly certain this is an instance where you just need new group files.

**Comment by ghost** [comment]
Could you please guide me through it? I am using the 2.3.6 version of Autowidget. When you refer to have a new group file, do you mean a widget group? Thanks

**Comment by drinfernoo** [comment]
Did you use AutoWidget prior to 2.3.6? Or is this a fresh install?

The error you're getting looks like a missing key in the path definition for an item... specifically 'art'. Are you trying to add paths to your group that have **no** art to display? Either way, this should never happen, so I'm suspicious of "malformed" group files of some kind.

**Comment by ghost** [comment]
Its a fresh install from your repo

**Comment by ghost** [comment]
No, I am trying to just have an autowidget with genres, countries... as you showed in the yt video

**Comment by ghost** [comment]
All based on my own movie library. I was just following you video of how to set up the add-on and I got stuck as it was not showing me to initialize the widget 

In addition, I've already uninstall and install autowidget just to see if that would fix it, however no green signs at all :(

**Comment by drinfernoo** [comment]
So, for one thing, that video is outdated, referring instead to the 1.x versions. You'll want this video instead if you need guidance with setting up the add-on: https://youtu.be/X3HSxTYPrzA

I suppose to try and troubleshoot, I need two things: your `kodi.log` file (not screenshots, but a pastebin or something is fine), and a zipped copy of the folder at `special://userdata/addon_data/plugin.program.autowidget/`.

I can't imagine why you would be having this issue, but I can only *guess* there's something wrong with your files 🤷🏽‍♀️

**Comment by NicksonStreet** [comment]
The message you just sent through is gone! Idk why :/. I am watching the updated yt video tho. So... I read that you need the kodi.log file? and the special://userdata/addon_data/plugin.program.autowidget/movies-1599334763.45.group. Am I correct? Could you please tell me where I can find those files so I can send it to you for troubleshooting. I am going to restart from scratch the autowidget and follow the steps from the updated video 👍

**Comment by ghost** [comment]
Here are the userdata/addon_data/plugin.program.autowidget files: 

[b6df83bb-186d-48df-92f6-7d471e161ded.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5179039/b6df83bb-186d-48df-92f6-7d471e161ded.zip)
[movies-1599360291.28.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5179040/movies-1599360291.28.zip)

Here is kodi.log
[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/5179045/kodi.log)

**Comment by drinfernoo** [comment]
Both your `.group` and `.widget` look fine, and both of them contain the appropriate keys, including the one which you initially showed an error from...

But the `.log` file you included doesn't contain any errors 🤔

**Comment by ghost** [comment]
I was just messing around with everything of the autowidget and I figured that if I add sub menu like: Genre or so, where the there is no thumbnails it will not function. I just added the recently added menu and it worked just fine,  also I included Sets and it is working as well. But when I want to cycle perhaps genre and countries it shows the error. I saw it on the outdated video but on the recent one you did not add the sub menu of genres. I dont know if it should work with it or it is not mean to. 

What I will do is to restart from scratch all my kodi because by sorting out the autowidget issue I really made a mess in my kodi with bunch of paths and other stuff so I will make sure this time to follow up your updated videos. If I encounter any other issues I'd let you know! Thank u so much for your time!
