### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ComradeSerg** [drinfernoo/plugin.program.autowidget#56]
Hi buddy. I already logged this unicode display issue and you fixed it. I recently reinstalled Kodi, installed Autowidget and was surprised to find the issue returned - I can create Autowidget Group in unicode, but can't use it.  I also checked the dev repository but there the same issue. I don't understand what has changed. I am attaching a debug log, you can notice issue starting on line 846, 1118, 1349.

[kodi.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5397937/kodi.zip)

**Comment by drinfernoo** [comment]
That error should be fixed as of `0.0.1059`, as mentioned in the previous issue you opened. This log shows that you have `2.3.6` installed, which was the version when you opened the first issue, before I made any fixes. I've merged the fixes in as `2.3.7`.

**Comment by ComradeSerg** [comment]
Understood, but why you prod repository offers only version 2.3.6? 2.3.7 is not released yet?

**Comment by drinfernoo** [comment]
Whoops, I pushed to GitHub but not to the repo 🤦 All fixed now.
