### ISSUE TITLE
[Bug] Unicode issue in translation file when trying to edit group

### ISSUE THREAD

**Issue by ComradeSerg** [drinfernoo/plugin.program.autowidget#64]
Hi buddy,
Last time you fixed a bug with unicode and now everything is fine. But I noticed a file with translation and wanted to create my own. And everything 
[kodi.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5604612/kodi.zip)
is ok with the exception of one point - when I try to edit a group - I get a unicode error. I checked if there is such an error with your file (resource.language.es_es/strings.po) and found that there is no error. This is probably due to the fact that in the case "resource.language.es_es/strings.po", when the group editing menu is called, there are no unicode characters. In my case, all characters are unicode. Logs attached (probably line 333)

I hope I didn't bore you with the unicode error :)

**Comment by ComradeSerg** [comment]
Oops, logs inserted in wrong place :)

**Comment by drinfernoo** [comment]
I see the issue, and will try to fix it soon.

**Comment by drinfernoo** [comment]
@ComradeSerg Could you try the latest devrepo release? It should be 0.0.1089.

**Comment by ComradeSerg** [comment]
Just installed 0.0.1089 (3.2) from dev. What is strange, right after installation I see version - 0.0.1089, but if I'll open AutoWidget second time I see only version 3.2. And issue still persist, logs attached.

[kodi.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5625742/kodi.zip)

**Comment by drinfernoo** [comment]
@ComradeSerg I'm not sure what you mean by "3.2". There has not been a 3.2 version of this addon.

My guess is that you have auto-updates turned on, so that it is automatically updating to the latest version instead of the devrepo version, and have misquoted the version you're seeing.

**Comment by ComradeSerg** [comment]
Sorry, my misatke, I was confused with version because when I selected AutoWidget from dev repository, by default before installation it shows version 0.0.1089 (probably latest), but after click on it - pop up appears with first offered version is 3.0.2 and I installed 3.0.2. Now I found if I'll scroll down I can find 0.0.1089, and I installed 0.0.1089. Also I turned off auto update as you offered. But unfortunately issues persist. Logs attached. Probably from line 770.
[kodi.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5631682/kodi.zip)

**Comment by drinfernoo** [comment]
Can you send the `.group` file for the group you're trying to manage?

**Comment by ComradeSerg** [comment]
It's youtube channel

[-1606938207.11.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/5632217/-1606938207.11.zip)

**Comment by drinfernoo** [comment]
Can you try the latest devrepo build?

**Comment by ComradeSerg** [comment]
Well done! This time I'm able to invoke edit menu.

**Comment by drinfernoo** [comment]
Great 👍 This will end up getting merged as part of 3.1.0, later this week.

**Comment by ComradeSerg** [comment]
Cool, will wait for next release.
