### ISSUE TITLE
[Request] Easy to forget how it works

### ISSUE THREAD

**Issue by djay** [drinfernoo/plugin.program.autowidget#65]
For people new to autowidget or those that haven't used it in awhile, it can be hard to work out how to use it.
The first thing you do is either open the plugin or the plugin settings and neither of these tell you how to add groups via context menu inside other apps, or how to get groups in your skin. or what a group is

# Options
1. [x] Instructions in readme?
2. [ ]  Instructions in settings?
3. [ ]  instructions page from menu item in plugin
4. [x] hint menu items?
   - e.g. "My Groups" > ```==To add a group, use context menu inside other addons==```
   - e.g. "Active Widgets" > ```==Add "My Group" > "{name}" as a widget in your skin==```
5. [ ] add a way to create/add-to a group inside the plugin?

**Comment by drinfernoo** [comment]
I think you're probably totally right... And to be honest, I thought I had a lot more documentation around than I realize I do 😅

Regarding the readme, I think that's a totally reasonable place for many people to get instructions, but it's also not a place that's very visible to Kodi users who don't *also* use GitHub.

Instructions in settings isn't impossible, but would likely only take the form of help text related *to* it's respective setting. Gaia does this.

Regarding the rest, these (or similar solutions) are all things that I did used to have implemented in earlier versions... but ended up removing them, mostly for simplicity. I found that it was less complicated (in my opinion) when there was only a *single* entry point to the main addon functions, and the context menu fit that bill nicely. Essentially, if you can get your grubby little context menu on it, it should work with AutoWidget.

That being said, I'm definitely not *against* this, but I typically just send people here: https://forum.kodi.tv/showthread.php?tid=352934 😉

**Comment by djay** [comment]
I think of those options putting in a fake menu item to tell people how it
works I think might work the best. When clicked it could also give a more
full discription?
Totally agree using only context menu makes the tool easier. It's just hard
to work out.
So a "hey it's not here, look over here instead" ?

**Comment by djay** [comment]
@drinfernoo I put some instructions in the readme in #67 but don't know enough about creating menu items to attempt the 4th suggestion

**Comment by drinfernoo** [comment]
In addition to the commits that got referenced here (which will be merged to `master` for 3.3.0), I've gone ahead and updated the wiki with a bit more detailed instructions on usage :+1:

I haven't yet decided on whether to add hint labels inside the settings dialog or menus, but that should be easy if it gets decided on.
