### ISSUE TITLE
[Request] Path names require too much editing when adding as widgets to a skin

### ISSUE THREAD

**Issue by djay** [drinfernoo/plugin.program.autowidget#66]
When you add a widget, its suggested name comes from the menu item name. With autowidget the names end up something like "Cycling Path from Recently Added". That doesn't look so good in my skins so I need to edit it. On a PC thats pretty painless. On a Smart TV with a remote that's a pain. When adding many widgets its really painful.

If it instead said "Recently added (cycled)" then it's a better default and if I want it to say "Recently Added" then its also easier to delete rather than move the cursor then delete.

In addition I think the name "static" is not so obvious and perhaps should just be with no extra name attached?

I'd suggest Rotating is perhaps better than Cycled but that could just be me. "One big list" is perhaps better than merged. Having random as its own menu items seems to make more sense to me since random is not really cycled.

e.g.

- Recently Added
- Recently Added (Rotating)
- Recently Added (Random)
- Recently Added (One big list)

**Comment by drinfernoo** [comment]
Good feedback, I'll take them into consideration 👍

**Comment by drinfernoo** [comment]
I think this should be safe to close now 😁
