### ISSUE TITLE
[Bug] widget not moved along 

### ISSUE THREAD

**Issue by ngpsherwood** [drinfernoo/plugin.program.autowidget#73]
Hello I love this addon but I make a widget on my front screen and I love that widget long difference between posters automatically but I make a shortcuts widget below  posters widget  and it's stop automatically  long  

Its a bug or something 

Thanks you

**Comment by drinfernoo** [comment]
I'm sorry, but you'll have to explain in more detail.

**Comment by ngpsherwood** [comment]
I'm sorry for my bad English 

I got a widget on my home screen and it's automatically moving along between every 1 minutes but if I add more widgets on home screen and it's stop automatically long

**Comment by drinfernoo** [comment]
I still don't know exactly what you mean, but what skin are you using?

To me this sounds like you're saying that the skin you use "rotates" through widget items periodically, but if that's not working, it would be a skin issue.

**Comment by ngpsherwood** [comment]
I use arctic horizon skin and if I use 1 widget on home screen  and its rotation  through widget but if I put 2 or more widget on homepage and it's not rotation anymore 
I hope its making sense then last comments

**Comment by drinfernoo** [comment]
That is a skin issue, then.
