### ISSUE TITLE
[Request] Confusing when background updates are happening

### ISSUE THREAD

**Issue by djay** [drinfernoo/plugin.program.autowidget#74]
**Is your feature request related to a problem? Please describe.**
There are times when a background update of a path is happening. When something stops playing. When you reload a skin. on startup. when you click next page. If you are waiting for it it's hard to know when its done or not. esp since updates to the widget could come from other places like the skin and they would reload an old copy of the path so you want to know that background updating is still getting the newer copy.

**Describe the solution you'd like**
Unobtrusive notice that autowidget is refreshing a path within a certain group in the background.

**Describe alternatives you've considered**
or
- a dummy tile could be used to say the update is happening
- mark up or alter names of the items in the path to show they are going to get updated
- in some circumstances do the update syncrhonously and then the skin will show a waiting on the widget. Still do background updates on playback and startup but perhaps any other time where the user has done a deliberate action to do an update (like skin reload or next page) then we set a flag to ensure that we don't do a background update in this case.

**Additional context**
Seems to come up in many issues where there is confusing if a widget was cache or if its just slow in background updating or something else is going on.

**Comment by djay** [comment]
fixed in #76
It shows not cached content as loading.
It doesn't really solve the problem where someone initiates a deliberate action to refresh.
It doesn't really show errors well.

**Comment by drinfernoo** [comment]
These should now be handled by #98 😉
