### ISSUE TITLE
[Request] Some requested widget updates don't happen due to min 5min cache

### ISSUE THREAD

**Issue by djay** [drinfernoo/plugin.program.autowidget#75]
**Is your feature request related to a problem? Please describe.**
If someone updates a path and then does a skin reload it will do a background update of the widget. If they do that again within 5min it won't do a background update because there is a mechanism to prevent looping updates then refreshes in the widget which is why 5min cache was put in

**Describe the solution you'd like**
Replace the 5min cache when a flag that when a path has been written to in the background that the next request for that path will read and not update, but any other request will update.
If we want to introduce longer cache times for certain items that hardly change then we'd need another another flag for times where the user has deliberately request some update. Like they used tools and forced reload. Or perhaps any update that happens outside of playback or startup?

**Describe alternatives you've considered**

**Additional context**

**Comment by drinfernoo** [comment]
I think this one may be covered by #98 as well.
