### ISSUE TITLE
[Bug] TMDB could not find item error message clicking extendend info in a TV widget

### ISSUE THREAD

**Issue by borisantelo** [drinfernoo/plugin.program.autowidget#77]
**Describe the bug**
Using Auramod skin in a TV related widget (with an autowidget path obviously) clicking on item from the list and choosing extended info appears the message TMDB could not find item, this doesn't happen with a movie widget neither with a TV widget with a path from another addon.

**To Reproduce**
1.  Go to an item from a TV list windget
2.  Click on Extended Info
3.  See error TMDB could not find item

**Expected behavior**
Show Extended info
**Screenshots**

**Details:**
  - What version of Kodi? Kodi 18
  - What skin is being used? Auramod
  - What device? (PC, Smartphone, Fire TV, Nvidia Shield, etc...) Odroid C2
  - What platform? (Android, iOS, Windows, OS X, Linux, etc...) Coreelec

**Additional context**

**Comment by drinfernoo** [comment]
I'll need a debug log before I can diagnose any further.

**Comment by borisantelo** [comment]
Sorry. This is the log https://paste.kodi.tv/acixukomup
It´s about the request of extended info for the TV series The good place 
Thanks

**Comment by drinfernoo** [comment]
I'm relatively certain that is because you're using OpenInfo, which has almost always had this issue... Not an AutoWidget issue.
