### ISSUE TITLE
[Enhancement] Let Cycling Widgets Pull from a Subset of Paths

### ISSUE THREAD

**Issue by drinfernoo** [drinfernoo/plugin.program.autowidget#79]
This would allow for choosing a subset of paths in a group, whenever a cycling widget is initialized (similar to a static widget), so that one large group can be used for various widgets.

This would likely have to serialize the paths (probably by ID) into the `.widget` file, which would then be referenced in the refreshing process, rather than the `.group`.

**Comment by drinfernoo** [comment]
And this one should be working in 3.3.0 as well 🎉 

It did take some finagling of the `.widget` file format, which is cleaner and easier to work with in general, I think... but will likely require many widgets to be re-pointed, as it is not very backwards-compatible with the old format.

**Comment by BinaryAssault** [comment]
Out of curiosity, why not create a converter to sustain backwards compatibility? Or even a standalone tool to handle it

**Comment by drinfernoo** [comment]
@BinaryAssault It's possible that I can make something work, but it seems like it would be more of a hassle to "run them through the converter" than to just repoint the widget 😅

Basically, each widget type before handled things pretty messily (in particular, "paged" widgets), in that they would store the entire definition of their current path inside, and change out the whole definition any time there was a refresh or update. The changes that made it possible to address this issue, made it so that all that is stored in the widget is a reference to the path ID, meaning the `.widget` files are much simpler, but no longer have the same structure. Pointing a new widget (at the same group and action, as groups should have had no breaking changes) will do just fine.

**Comment by drinfernoo** [comment]
@BinaryAssault I've actually implemented a very simple automatic conversion, which should handle fixing the format of your old widgets, so that they match the new format 🎉 

This should ideally include any existing Static, Cycling, and/or Merged widgets, and should happen with the first skin reload (or Kodi reboot) after you take the 3.3.0 update :+1:

**Comment by BinaryAssault** [comment]
Job well done mate. Additional nice to have: auto backup prior to converting. Even if converting fails and the new file is foobar'd, the old one is preserved.

**Comment by drinfernoo** [comment]
Either way, fixing it will be as simple as pointing a new widget.

I've also implemented a rudimentary "error state" widget, to indicate if there was an error loading it. This will typically mean a fresh re-pointing is necessary.
