### ISSUE TITLE
[Bug] Autowidget shows error message when adding a widget

### ISSUE THREAD

**Issue by rizreflects** [drinfernoo/plugin.program.autowidget#82]
**Describe the bug**
If I add a widget from 'my groups' an error message pops up. I have tested it with static, cycling and merged widgets, they all return with an error message. 

**To Reproduce**
-Add a few lists to your autowidget group.
-Set it as a widget. (In my case I picked cycling then random).
-You will see an autowidget error message 

**Details:**
  - What version of Kodi? 19.0
  - What skin is being used? Arctic Horizon (it's not the official skin, but one that has been slightly altered to work on Kodi 19).
  - What device? PC
  - What platform? Windows

**Additional context**
My log file is below:

https://paste.kodi.tv/zalebexihe

**Comment by drinfernoo** [comment]
I'm currently investigating this, but believe it to be an issue in the path-supplying add-on (Seren in this case).

**Comment by drinfernoo** [comment]
@rizreflects If you're able, can you send a copy of the `.group` file for the widget you're using?

**Comment by rizreflects** [comment]
I've uploaded it to my onedrive for you. 

https://1drv.ms/u/s!AgpGD5FbtkrWm3bGi8v5VE9ABMU4?e=KjqAI8

**Comment by drinfernoo** [comment]
Should be fixed in 3.1.3 🎉
