### ISSUE TITLE
Dynamic group labels

### ISSUE THREAD

**Issue by avsha114** [drinfernoo/plugin.program.autowidget#83]
Hi!

Is it possible to create a group for random cycling and make it's label changed to the current playlist's name?
For example, I created a widget group from FEN called "Because you watched..." and inside there are 10 widgets called "Because you watched Dexter" or "Because you watched GOT". So I want the widget label to be the specific playlist label.
Is this an option? I searched but didn't find anything

**Comment by drinfernoo** [comment]
https://youtu.be/J7i4bW8H-kU

**Comment by drinfernoo** [comment]
To add to this, there is also "Tools -> Toggle Skin Debugging" inside AutoWidget, that will help you find the container ID for your widget.
