### ISSUE TITLE
Widgets open to File Path when pointing to Library

### ISSUE THREAD

**Issue by JSAKelley** [drinfernoo/plugin.program.autowidget#85]
Using Kodi 18.9 with a MySQL database populated using TMDBHelper Add-On.

Widgets created using a playlist of shows is opening to file view (i.e. SHOWNAME.STRM) instead of the Library view.

It should be noted that when opening that show directly from the playlist it opens correctly.

**Comment by drinfernoo** [comment]
Does thIs happen with a library *not* managed by MySQL? I have tested against ones fed from the normal Kodi library... but it's been awhile. I may need to do some further testing 🤔

**Comment by JSAKelley** [comment]
I'm not sure. I'll test it out.

I have a PC that I use to run Kodi 24/7 and control the library updates.
This is also the MySQL server.  When I do it on that PC it works as
expected.

I set up another client on a fire stick I had lying around and it's broke
on that too.

I should note too that the library is stored on a network share on storage
attached to my router.

**Comment by JSAKelley** [comment]
So either something fixed this in your update or me adding my library paths
on my clients did it. Either way I have it working now!

**Comment by drinfernoo** [comment]
Awesome! I didn't touch anything related to this, so 🤷🏼‍♀️

In any case, glad it works now 👍
