### ISSUE TITLE
[Bug] Autowidget Error

### ISSUE THREAD

**Issue by luckylukz02** [drinfernoo/plugin.program.autowidget#87]
Autowidget fails to load widgets with error to see log

**To Reproduce**
Start device with widgets to load
Or Open Autowidget

**Expected behavior**
Load widgets and be able to open addon

**Details:**
Kodi 20 Alpha1
Arctic Horizon
Intel NUC 8
Libreelec

**Additional context**
Having to run Libreelec 11 - Kodi 20 Alpha1 due to compatibility of HDR on device.

Log:

https://paste.kodi.tv/uqiyedisak.kodi

**Comment by drinfernoo** [comment]
Ah, it appears that Kodi Six has now updated to handle the new implementation of `xbmc.translatePath`... Odd that I'm not seeing this happen in Kodi 19, however. I'll address it directly in the future, and it should prevent any further issues.

**Comment by luckylukz02** [comment]
Thanks for the fix all working again 👍
