### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jojobrogess** [drinfernoo/plugin.program.autowidget#89]
**Describe the bug**
`plugin.program.autowidget\resources\lib\common\utils.py` 
uses xbmc.translatePath and should use xbmcvfs.translatePath instead. Or at least that's what the Kodi logs keep telling me:

`WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.`

**To Reproduce**
1.  Open Kodi.
2.  Check Logs.

I tried switching it myself, but idk how to define things. Or how to read any of it lol. 
Idk what it does, but autowidget still works for me so it probably hasn't been depreciated yet. but I wanted to post to make sure.

**Comment by drinfernoo** [comment]
Update. This was fixed in 3.1.8.1 back in April.

EDIT: I've only just realized that 3.1.8.1 never made it to repo. I've pushed 3.1.9 to fix this.
