### ISSUE TITLE
AutoWidget throwing error when removing playback progress from Seren's context menu [BUG]

### ISSUE THREAD

**Issue by ivarbrandt** [drinfernoo/plugin.program.autowidget#91]
When removing an items' playback progress in finish watching (movies) section using Seren's context menu, AutoWidget would throw an error. It would also throw errors when the AutoWidget would refresh. I would also sometimes not even load the widget even though there was other movies in the finish watching section. 

It's important to note that the widget I think is throwing errors is a merged widget consisting of finish watching sections for movies and shows inside Seren.

[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/6683026/kodi.log)

**Comment by drinfernoo** [comment]
I think I'll need to look a bit further into this, but in the meantime, could you create an AutoWidget backup and upload it here? There's a backup option in AutoWidget's settings 😉

**Comment by ivarbrandt** [comment]
I can do that. I already used the option 'clean old widget files' in an attempt to fix the error. Would the backup still be valuable knowing this?

**Comment by ivarbrandt** [comment]
Here's the backup.

[AutoWidget backup.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/6683054/AutoWidget.backup.zip)

**Comment by drinfernoo** [comment]
Actually, I was hoping for the "old" `.widget` files that you cleaned up 😅 

Are you still having this issue?

EDIT: I just realized... the backup function doesn't even save anything but `.group` files 🤦 I've updated it on the `develop` branch, but haven't merged that change to `master` yet. It should be available in 3.3.0 (whenever that shows up), or you can grab any release from the devrepo after 0.0.1264.

**Comment by drinfernoo** [comment]
It should now be possible to do a more comprehensive backup, as of 3.3.0

**Comment by ivarbrandt** [comment]
I don't have the back up files. I stopped using widgets altogether. Makes my Kodi faster.
