### ISSUE TITLE
[Bug] problem when trakt lists are set to random.

### ISSUE THREAD

**Issue by rizreflects** [drinfernoo/plugin.program.autowidget#93]
**Describe the bug**

This bug only occurs when a trakt list is set to display movies at random, (as opposed to rank or release date). Autowidget will retrieve the list as normal. However, it tends randomise 30-40 seconds after the list has been retrieved. Furthermore, this does not occur every single time, but enough that it becomes a problem. 

In practice, the list will randomise as you are already browsing through it. So the movie you are currently on will change to a different one as you scroll through the widgets. 

**To Reproduce**
Bug is difficult to reproduce as it does not occur 100% of the time. That being said, simply add a few lists that are all set to random. Keep refreshing and you will see the problem occur sooner or later.

**Expected behavior**
Ideally, I would like autowidget to randomise the lists before displaying them on kodi. Currently, it seems that autowidget displays the list first and then randomises the movies a few seconds later.

**Screenshots**
Will be difficult since it's hard to predict when the problem will occur. However, I can upload a video if you need me to. 

**Details:**
  - What version of Kodi? CoreELEC 19
  - What skin is being used? Problem occurs on Arctic Horizon and also Arctic zephyr 2 resurrection.
  - What device? Odroid n2+
  - What platform? CoreELEC

I don't know how well I explained the problem, it's a difficult one to explain properly.

**Comment by drinfernoo** [comment]
This is a skin issue, and will likely happen even with widgets from other sources, if they're sorted randomly.

I do have an issue open already regarding sorting lists (#80) ahead of time, but haven't even gotten to it.

**Comment by Zhiro90** [comment]
Thanks for your answer Any idea how they were working before the update?
