### ISSUE TITLE
Ability to create subfolders

### ISSUE THREAD

**Issue by milohelmes** [drinfernoo/plugin.program.autowidget#95]
I would love to be able to create widget groups inside widget groups. The main reason being organisation. An example would be creating a widget group called "Popular Movies" inside a group called "Movies" where I can place widgets from multiple addons. 

Another example would be using AutoWidget as a way to create playlists. The Add to widgetgroup shortcut in the context menu could then be used to place a movie inside a folder called "Horror" inside a folder called "Movies"

Perhaps the addition of a "Create subwidget group" action inside the AutoWidget addon would be a good addition too.

**Comment by drinfernoo** [comment]
Duplicate of #28.
