### ISSUE TITLE
3.3 Breaks some widgets [Bug]

### ISSUE THREAD

**Issue by Zhiro90** [drinfernoo/plugin.program.autowidget#96]
**Describe the bug**
After updating, some previously working widgets from groups fail to load and show the error pictured in the screenshots. The failing group contains "Newly added" from Both Netflix and HBO Max plugins. Other widget groups containing widgets from these plugins didn't fail.  Also, the backup zip generated by the backup tool is filled with cache and history files (attached)
[BACK.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/6841402/BACK.zip)
.

**To Reproduce**
1 Add Categories form Netflix Plugin to a autowidget group
2 Add to homescreen (Merged, Cycling or Random)

**Expected behavior**
The Widget shows its contents.

**Screenshots**
https://imgur.com/a/Dob4t3u

**Details:**
* Kodi Leia
* Auramod
* Windows 7 PC

**Additional context**
Broken Widget Backup
{
    "paths": [
        {
            "target": "widget", 
            "color": "white", 
            "label": "Recently added NETFLIX", 
            "content": "files", 
            "window": "videos", 
            "version": "3.3.0", 
            "file": {
                "plot": "Discover the latest content added.", 
                "filetype": "directory", 
                "art": {
                    "icon": "DefaultRecentlyAddedMovies.png"
                }, 
                "votes": "0", 
                "file": "plugin://plugin.video.netflix/directory/video_list_sorted/recentlyAdded/1592210/"
            }, 
            "id": "recently_added_netflix-1626640947.62"
        }, 
        {
            "target": "widget", 
            "color": "white", 
            "label": "Just Added HBO", 
            "content": "videos", 
            "version": "3.3.0", 
            "file": {
                "plot": "[B]Just Added[/B]", 
                "votes": "0", 
                "art": {
                    "fanart": "special://home/addons\\slyguy.hbo.max\\fanart.jpg", 
                    "poster": "special://home/addons\\slyguy.hbo.max\\icon.png", 
                    "thumb": "special://home/addons\\slyguy.hbo.max\\icon.png", 
                    "landscape": "special://home/addons\\slyguy.hbo.max\\icon.png", 
                    "icon": "special://home/addons\\slyguy.hbo.max\\icon.png"
                }, 
                "title": "[B]Just Added[/B]", 
                "filetype": "directory", 
                "file": "plugin://slyguy.hbo.max/?_=page&label=Just%20Added&slug=urn%3ahbo%3apage%3ajust-added"
            }, 
            "id": "just_added_hbo-1626641025.04"
        }, 
        {
            "target": "widget", 
            "color": "white", 
            "label": "Recent Media SHS", 
            "content": "files", 
            "window": "programs", 
            "version": "3.3.0", 
            "file": {
                "filetype": "directory", 
                "art": {
                    "fanart": "special://home/addons/script.skin.helper.widgets/fanart.jpg", 
                    "thumb": "DefaultMovies.png", 
                    "icon": "DefaultMovies.png"
                }, 
                "votes": "0", 
                "file": "plugin://script.skin.helper.widgets/?action=recent&mediatype=media"
            }, 
            "id": "recent_media_shs-1626641130.02"
        }
    ], 
    "art": {
        "fanart": "special://home/addons\\plugin.program.autowidget\\resources\\media\\fanart\\folder-sync.png", 
        "poster": "special://home/addons\\plugin.program.autowidget\\resources\\media\\poster\\folder-sync.png", 
        "banner": "special://home/addons\\plugin.program.autowidget\\resources\\media\\banner\\folder-sync.png", 
        "thumb": "special://home/addons\\plugin.program.autowidget\\resources\\media\\icon\\folder-sync.png", 
        "icon": "special://home/addons\\plugin.program.autowidget\\resources\\media\\icon\\folder-sync.png"
    }, 
    "label": "Dashboard - 2 Novedades", 
    "content": "files", 
    "version": "3.3.0", 
    "type": "widget", 
    "id": "dashboard_-_2_novedades-1626640940.18"
}

===========
Relevant Kodi.log
2021-07-19 08:22:05.039 T:8608  NOTICE: plugin.program.autowidget: [ mode: force ]
2021-07-19 08:22:05.095 T:10152   ERROR: C:\Z\Apps\Program Files\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2021-07-19 08:22:05.189 T:8608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "C:\Z\Apps\Program Files\Kodi\portable_data\addons\plugin.program.autowidget\main.py", line 13, in <module>
                                                router.dispatch(_plugin, _handle, _params)
                                              File "C:\Z\Apps\Program Files\Kodi\portable_data\addons\plugin.program.autowidget\resources\lib\common\router.py", line 95, in dispatch
                                                refresh.refresh_paths(notify=True, force=True)
                                              File "C:\Z\Apps\Program Files\Kodi\portable_data\addons\plugin.program.autowidget\resources\lib\refresh.py", line 256, in refresh_paths
                                                widget_def["id"], widget_def=widget_def, paths=paths, force=force
                                              File "C:\Z\Apps\Program Files\Kodi\portable_data\addons\plugin.program.autowidget\resources\lib\refresh.py", line 225, in refresh
                                                path_label = manage.get_path_by_id(path_id, group_id).get(
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2021-07-19 08:22:05.222 T:10152   ERROR: C:\Z\Apps\Program Files\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,

**Comment by drinfernoo** [comment]
Your widget (`80d10be4-ba5d-45aa-8d2d-96b0d90c4a4d.widget`)is looking for a group with the ID `novedades-1625736675.56`, which I don't see in your backup... Have you mentally edited any of the `.group` files? I'm not sure what's happening here, so I might need to look a bit closer later this evening, but it should be fixed by repointing your widget.

The backup zip including all files was a deliberate change, so that they can more easily be used (by me) for debugging, as I can now get a full picture of your setup 😉

**Comment by Zhiro90** [comment]
Oh haven't edited the backups manually, only deleted all of my groups from the zip and just left one broken and one working. Here's the complete backup. Sorry for the confusion.

[BACKUP2.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/6841885/BACKUP2.zip)

**Comment by drinfernoo** [comment]
Ok... so from what I can see here:

Your widget (`80d10be4-ba5d-45aa-8d2d-96b0d90c4a4d`) is a Merged Widget:
```json
{
    "group": "novedades-1625736675.56", 
    "refresh": 2.0, 
    "version": "3.3.0", 
    "action": "merged", 
    "path": [
        "recently_added_netflix-1625736683.75"
    ], 
    "id": "80d10be4-ba5d-45aa-8d2d-96b0d90c4a4d"
}
```
This widget has a single path (`recently_added_netflix-1625736683.75`), which is from the group `novedades-1625736675.56` (not the group you pasted into your original comment). For one thing, this seems like an odd usage of a Merged Widget, and would likely be better suited by a Static Widget... since the group only contains that same single path:
```json
{
    "paths": [
        {
            "target": "widget", 
            "color": "white", 
            "label": "Recently added NEtflix", 
            "content": "files", 
            "window": "videos", 
            "version": "3.2.3", 
            "file": {
                "plot": "Discover the latest content added.", 
                "filetype": "directory", 
                "art": {
                    "icon": "DefaultRecentlyAddedMovies.png"
                }, 
                "votes": "0", 
                "file": "plugin://plugin.video.netflix/directory/video_list_sorted/recentlyAdded/1592210/"
            }, 
            "id": "recently_added_netflix-1625736683.75"
        }
    ], 
    "art": {
        "fanart": "special://home/addons\\plugin.program.autowidget\\resources\\media\\fanart\\folder-sync.png", 
        "poster": "special://home/addons\\plugin.program.autowidget\\resources\\media\\poster\\folder-sync.png", 
        "banner": "special://home/addons\\plugin.program.autowidget\\resources\\media\\banner\\folder-sync.png", 
        "thumb": "special://home/addons\\plugin.program.autowidget\\resources\\media\\icon\\folder-sync.png", 
        "icon": "special://home/addons\\plugin.program.autowidget\\resources\\media\\icon\\folder-sync.png"
    }, 
    "label": "Daxshboard - 2 Novedades", 
    "version": "3.2.3", 
    "type": "widget", 
    "id": "novedades-1625736675.56"
}
```
That being said, *for me*, Netflix -> Recently Added" is **empty**, which caused a different error (which I'm about to push a fix for)... But I am unable to reproduce the error you got, and don't see how it could be possible, based on the files you sent in your backup zip.

Could you try updating to 3.3.2, and if you still get this behavior, can you send a full log file?

**Comment by Zhiro90** [comment]
I'll update and report later. the merged widget with only one element comes from deleting one by one the rest of the elements from the widget group. It originally had recently added from HBO max and recently added media from skin library service. Tried many variations adding and removing paths and ended with only netflix left and it still had errors. 

that's why I originally deleted some groups from the backup, because I set up so many group variations and test groups trying to make it work it would just clutter the zip file.

 For reference, non working: dashboard - 2 novedades , dashXboard - 2 novedades , live TV.

working: the rest.

**Comment by Zhiro90** [comment]
With the update, the widgets that failed because of empty netflix lists work again. The "live TV" widget still failed due the twitch "now live" path returning nothing online. Once removed from the group it works again, so it must be related to empty lists perhaps.  Thank you so much

**Comment by drinfernoo** [comment]
Did they fail with an error as before, or just "drop out"?

**Comment by Zhiro90** [comment]
With an error as before 
![screenshot002](https://user-images.githubusercontent.com/25686691/126380910-7aafbcd0-0413-4270-bc6e-b2bd287fae88.png)

**Comment by drinfernoo** [comment]
Can you get me a fresh log?

**Comment by Zhiro90** [comment]
Here's the log. Added groups backup
[kodi.log](https://github.com/drinfernoo/plugin.program.autowidget/files/6851463/kodi.log)
[BACK3.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/6851477/BACK3.zip)

**Comment by drinfernoo** [comment]
It really seems like something's not right here. I copied in the associated files for that widget into my setup, and was able to get it working. I did have to clear the cache... have you tried that?

**Comment by Zhiro90** [comment]
Clearing cache solved the issue! Thanks again!
