### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sdstreams** [drinfernoo/plugin.program.autowidget#99]
Update: I went back to 3.3.1 and its working again.
---------------------------------------------------------------
**Describe the bug**

When I go into my video addons and click on AutoWidget I get an error. I have uninstalled then reinstalled without any issues but trying to open the addon I get an error. Been using for well over half a year without any issues just started with the current update.

**To Reproduce**
Go to Video addons clicked on AutoWidget then error see log

**Expected behavior**
Addon usually opens without any error or issue.

**Screenshots**

**Details:**
  - What version of Kodi? 18.8
  - What skin is being used? skin.arctic.zephyr.mod
  - What device? Nvidia Shield and FireStick 4k
  - What platform? Android

**Additional context**
[Kodi Log](https://pastebin.com/raw/MKxxLUYE)

**Comment by drinfernoo** [comment]
Ah, you know what... I hadn't even thought if this 🤦 It's an issue where I've written code that isn't Python 2.7-compatible, and I've been primarily testing in Kodi Matrix, which uses Python 3.8. Let me see if I can come up with a more compatible way.

**Comment by sdstreams** [comment]
Thank you for looking into the issue. As always you are very appreciated for the great work you do.

**Comment by drinfernoo** [comment]
Should be fixed in 3.3.6. Just needed to adjust the logic I used in that method.
